# Generated by Django 5.0.1 on 2024-01-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='alt_email_1_company',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='alt_email_2_company',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='alt_fax_company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='alt_mobile_company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='alt_phone_company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cc_email_company',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='cell_company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_1_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_2_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_3_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='skypeID_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='x_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_employee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='alt_email_1_employee',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='alt_email_2_employee',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='alt_fax_employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='alt_mobile_employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='alt_phone_employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cc_email_employee',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cell_employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city_employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='facebook_employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_phone_employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='linkedin_employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='main_email_employee',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='main_phone_employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_1_employee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_2_employee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_3_employee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skypeID_employee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state_employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street_name_employee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street_number_employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='x_employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='alt_email_1_owner',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='alt_email_2_owner',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='alt_mobile_owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='alt_phone_owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='cc_email_owner',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='cell_owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='city_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='facebook_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='fax_owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='home_phone_owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='linkedin_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='main_email_owner',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='main_phone_owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='other_1_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='other_2_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='other_3_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='skypeID_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='state_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='street_name_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='street_number_owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='x_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='zip_owner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
