# Generated by Django 5.0.1 on 2024-01-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_time',
            new_name='start_datetime',
        ),
        migrations.RenameField(
            model_name='conferenceroom',
            old_name='room',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='month',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='year',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='confirmation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='default_free_hours',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='office',
            name='free_hours',
            field=models.PositiveIntegerField(help_text='carry over hours'),
        ),
        migrations.AlterField(
            model_name='office',
            name='term_lease',
            field=models.PositiveIntegerField(help_text='number of payments'),
        ),
    ]
