# Generated by Django 5.0.1 on 2024-03-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_booking_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='all_day',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
