# Generated by Django 5.0.3 on 2024-03-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_client_users_client_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='users',
            new_name='user',
        ),
    ]
