# Generated by Django 5.0.3 on 2024-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_building_select_default_alter_building_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='select_default',
            field=models.CharField(choices=[('CustomInput', '--- Custom Input ---'), ('West Boca Executive Suites', 'West Boca Executive Suites'), ('7777 Glade Road', '7777 Glade Road')], default='CustomInput', max_length=500),
        ),
    ]
