# Generated by Django 5.0.3 on 2024-04-05 17:00

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_remove_conferenceroom_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=apps.models.get_file_path),
        ),
    ]
